### ISSUE TITLE
where to download the trained models

### ISSUE THREAD

**Issue by sathish4ds** [iCVTEAM/PGNet#1]
Hi Team this is really great job can you please let me know where to download the trained models.

**Comment by xiechenxi99** [comment]
Thanks for your recognition, we have updated the goolge drive link in test part, https://drive.google.com/drive/folders/1hXwCvrdmvkaRePXWPTw5tjFXmrrzHPtt?usp=sharing .

**Comment by aviaisr** [comment]
Hi,
The link you sent downloads a directory called PGNet_DUT+HR-model-31~. Where are the PTH files in this directory?
Should I convert the data.pkl file? How? And where should I save the weights to run the test?
